export let role = 'admin';

export const teachersData = [
  {
    id: 1,
    teacherId: '1000000001',
    name: 'Khaled Ahasan',
    email: 'khaled.ahasan@example.com',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    phone: '5551111001',
    subjects: ['Math', 'Geometry'],
    classes: ['1B', '2A', '3C'],
    address: '123 Main St, Anytown, USA',
  },
  {
    id: 2,
    teacherId: '1000000002',
    name: 'Sophia Johnson',
    email: 'sophia.johnson@example.com',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    phone: '5551111002',
    subjects: ['English', 'Literature'],
    classes: ['4A', '5B'],
    address: '456 Oak St, Springfield, USA',
  },
  {
    id: 3,
    teacherId: '1000000003',
    name: 'Liam Martinez',
    email: 'liam.martinez@example.com',
    photo: 'https://randomuser.me/api/portraits/men/13.jpg',
    phone: '5551111003',
    subjects: ['Physics', 'Chemistry'],
    classes: ['6C', '7A'],
    address: '789 Pine St, Rivertown, USA',
  },
  {
    id: 4,
    teacherId: '1000000004',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    photo: 'https://randomuser.me/api/portraits/women/14.jpg',
    phone: '5551111004',
    subjects: ['Biology', 'Science'],
    classes: ['2B', '3A', '4C'],
    address: '12 Maple Ave, Hillview, USA',
  },
  {
    id: 5,
    teacherId: '1000000005',
    name: 'Noah Wilson',
    email: 'noah.wilson@example.com',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    phone: '5551111005',
    subjects: ['History', 'Civics'],
    classes: ['5A', '6B'],
    address: '34 Birch Rd, Lakewood, USA',
  },
  {
    id: 6,
    teacherId: '1000000006',
    name: 'Olivia Brown',
    email: 'olivia.brown@example.com',
    photo: 'https://randomuser.me/api/portraits/women/16.jpg',
    phone: '5551111006',
    subjects: ['Math', 'Algebra'],
    classes: ['1A', '2C'],
    address: '56 Elm St, Brookfield, USA',
  },
  {
    id: 7,
    teacherId: '1000000007',
    name: 'James Anderson',
    email: 'james.anderson@example.com',
    photo: 'https://randomuser.me/api/portraits/men/17.jpg',
    phone: '5551111007',
    subjects: ['Geography', 'Environmental Science'],
    classes: ['3B', '4A'],
    address: '78 Cedar Dr, Fairview, USA',
  },
  {
    id: 8,
    teacherId: '1000000008',
    name: 'Isabella Thomas',
    email: 'isabella.thomas@example.com',
    photo: 'https://randomuser.me/api/portraits/women/18.jpg',
    phone: '5551111008',
    subjects: ['Chemistry', 'Physics'],
    classes: ['7C', '8A'],
    address: '90 Walnut Ln, Greenfield, USA',
  },
  {
    id: 9,
    teacherId: '1000000009',
    name: 'Ethan Moore',
    email: 'ethan.moore@example.com',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    phone: '5551111009',
    subjects: ['Art', 'Design'],
    classes: ['1C', '5C'],
    address: '23 Aspen Ct, Meadowbrook, USA',
  },
  {
    id: 10,
    teacherId: '1000000010',
    name: 'Mia Lee',
    email: 'mia.lee@example.com',
    photo: 'https://randomuser.me/api/portraits/women/20.jpg',
    phone: '5551111010',
    subjects: ['Music', 'Choir'],
    classes: ['6A', '7B'],
    address: '45 Poplar St, Sunnyside, USA',
  },
  {
    id: 11,
    teacherId: '1000000011',
    name: 'Alexander White',
    email: 'alex.white@example.com',
    photo: 'https://randomuser.me/api/portraits/men/21.jpg',
    phone: '5551111011',
    subjects: ['Physical Education'],
    classes: ['3C', '4B'],
    address: '67 Willow Dr, Clearview, USA',
  },
  {
    id: 12,
    teacherId: '1000000012',
    name: 'Charlotte Harris',
    email: 'charlotte.harris@example.com',
    photo: 'https://randomuser.me/api/portraits/women/22.jpg',
    phone: '5551111012',
    subjects: ['Computer Science', 'Programming'],
    classes: ['8B', '9A'],
    address: '89 Chestnut Blvd, Riverview, USA',
  },
  {
    id: 13,
    teacherId: '1000000013',
    name: 'Benjamin Clark',
    email: 'ben.clark@example.com',
    photo: 'https://randomuser.me/api/portraits/men/23.jpg',
    phone: '5551111013',
    subjects: ['Math', 'Statistics'],
    classes: ['2A', '3B'],
    address: '101 Maple St, Crestwood, USA',
  },
  {
    id: 14,
    teacherId: '1000000014',
    name: 'Amelia Lewis',
    email: 'amelia.lewis@example.com',
    photo: 'https://randomuser.me/api/portraits/women/24.jpg',
    phone: '5551111014',
    subjects: ['Chemistry', 'Biology'],
    classes: ['4C', '5A'],
    address: '222 Oakwood Rd, Glenville, USA',
  },
  {
    id: 15,
    teacherId: '1000000015',
    name: 'Logan Young',
    email: 'logan.young@example.com',
    photo: 'https://randomuser.me/api/portraits/men/25.jpg',
    phone: '5551111015',
    subjects: ['Drama', 'Theater'],
    classes: ['6C', '7C'],
    address: '333 Pine Ln, Willowbrook, USA',
  },
  {
    id: 16,
    teacherId: '1000000016',
    name: 'Harper Walker',
    email: 'harper.walker@example.com',
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
    phone: '5551111016',
    subjects: ['Economics', 'Business'],
    classes: ['8A', '9B'],
    address: '444 Spruce Dr, Lakeview, USA',
  },
  {
    id: 17,
    teacherId: '1000000017',
    name: 'Lucas King',
    email: 'lucas.king@example.com',
    photo: 'https://randomuser.me/api/portraits/men/27.jpg',
    phone: '5551111017',
    subjects: ['English', 'Writing'],
    classes: ['1B', '2C'],
    address: '555 Sycamore St, Hillcrest, USA',
  },
  {
    id: 18,
    teacherId: '1000000018',
    name: 'Evelyn Scott',
    email: 'evelyn.scott@example.com',
    photo: 'https://randomuser.me/api/portraits/women/28.jpg',
    phone: '5551111018',
    subjects: ['History', 'World Studies'],
    classes: ['3A', '4B'],
    address: '666 Redwood Ave, Brookside, USA',
  },
  {
    id: 19,
    teacherId: '1000000019',
    name: 'Henry Adams',
    email: 'henry.adams@example.com',
    photo: 'https://randomuser.me/api/portraits/men/29.jpg',
    phone: '5551111019',
    subjects: ['Biology', 'Health'],
    classes: ['5C', '6A'],
    address: '777 Magnolia Blvd, Stonefield, USA',
  },
  {
    id: 20,
    teacherId: '1000000020',
    name: 'Avery Perez',
    email: 'avery.perez@example.com',
    photo: 'https://randomuser.me/api/portraits/women/30.jpg',
    phone: '5551111020',
    subjects: ['Physics', 'Robotics'],
    classes: ['7B', '9C'],
    address: '888 Dogwood Dr, Bayview, USA',
  },
];


export const studentsData = [
  {
    id: 1,
    studentId: "10000001",
    name: "Khaled Ahasan",
    email: "khaled.ahasan1@example.com",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    phone: "5551111001",
    grade: 5,
    class: "A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "10000002",
    name: "Sara Rahman",
    email: "sara.rahman@example.com",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    phone: "5551111002",
    grade: 6,
    class: "B",
    address: "456 Oak St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "10000003",
    name: "John Doe",
    email: "john.doe@example.com",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    phone: "5551111003",
    grade: 7,
    class: "C",
    address: "789 Pine St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "10000004",
    name: "Aisha Khan",
    email: "aisha.khan@example.com",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    phone: "5551111004",
    grade: 8,
    class: "D",
    address: "321 Cedar St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "10000005",
    name: "Michael Smith",
    email: "michael.smith@example.com",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    phone: "5551111005",
    grade: 5,
    class: "E",
    address: "654 Birch St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "10000006",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    phone: "5551111006",
    grade: 6,
    class: "F",
    address: "987 Maple St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "10000007",
    name: "David Johnson",
    email: "david.johnson@example.com",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    phone: "5551111007",
    grade: 7,
    class: "G",
    address: "135 Walnut St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "10000008",
    name: "Sophia Brown",
    email: "sophia.brown@example.com",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    phone: "5551111008",
    grade: 8,
    class: "H",
    address: "246 Spruce St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "10000009",
    name: "James Wilson",
    email: "james.wilson@example.com",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    phone: "5551111009",
    grade: 5,
    class: "I",
    address: "357 Willow St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "10000010",
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    phone: "5551111010",
    grade: 6,
    class: "J",
    address: "468 Elm St, Anytown, USA",
  },
  {
    id: 11,
    studentId: "10000011",
    name: "Ethan Lee",
    email: "ethan.lee@example.com",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    phone: "5551111011",
    grade: 7,
    class: "K",
    address: "579 Aspen St, Anytown, USA",
  },
  {
    id: 12,
    studentId: "10000012",
    name: "Isabella Clark",
    email: "isabella.clark@example.com",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    phone: "5551111012",
    grade: 8,
    class: "L",
    address: "680 Chestnut St, Anytown, USA",
  },
  {
    id: 13,
    studentId: "10000013",
    name: "William Harris",
    email: "william.harris@example.com",
    photo: "https://randomuser.me/api/portraits/men/13.jpg",
    phone: "5551111013",
    grade: 5,
    class: "M",
    address: "791 Cypress St, Anytown, USA",
  },
  {
    id: 14,
    studentId: "10000014",
    name: "Mia Lewis",
    email: "mia.lewis@example.com",
    photo: "https://randomuser.me/api/portraits/women/14.jpg",
    phone: "5551111014",
    grade: 6,
    class: "N",
    address: "802 Magnolia St, Anytown, USA",
  },
  {
    id: 15,
    studentId: "10000015",
    name: "Alexander Walker",
    email: "alexander.walker@example.com",
    photo: "https://randomuser.me/api/portraits/men/15.jpg",
    phone: "5551111015",
    grade: 7,
    class: "O",
    address: "913 Poplar St, Anytown, USA",
  },
  {
    id: 16,
    studentId: "10000016",
    name: "Charlotte Hall",
    email: "charlotte.hall@example.com",
    photo: "https://randomuser.me/api/portraits/women/16.jpg",
    phone: "5551111016",
    grade: 8,
    class: "P",
    address: "102 Maplewood St, Anytown, USA",
  },
  {
    id: 17,
    studentId: "10000017",
    name: "Benjamin Allen",
    email: "benjamin.allen@example.com",
    photo: "https://randomuser.me/api/portraits/men/17.jpg",
    phone: "5551111017",
    grade: 5,
    class: "Q",
    address: "213 Redwood St, Anytown, USA",
  },
  {
    id: 18,
    studentId: "10000018",
    name: "Amelia Young",
    email: "amelia.young@example.com",
    photo: "https://randomuser.me/api/portraits/women/18.jpg",
    phone: "5551111018",
    grade: 6,
    class: "R",
    address: "324 Sequoia St, Anytown, USA",
  },
  {
    id: 19,
    studentId: "10000019",
    name: "Henry King",
    email: "henry.king@example.com",
    photo: "https://randomuser.me/api/portraits/men/19.jpg",
    phone: "5551111019",
    grade: 7,
    class: "S",
    address: "435 Alder St, Anytown, USA",
  },
  {
    id: 20,
    studentId: "10000020",
    name: "Grace Wright",
    email: "grace.wright@example.com",
    photo: "https://randomuser.me/api/portraits/women/20.jpg",
    phone: "5551111020",
    grade: 8,
    class: "T",
    address: "546 Dogwood St, Anytown, USA",
  },
];


export const parentsData =[
    
];

export const subjectsData =[
    
];

export const classesData =[
    
];

export const lessonsData =[
    
];

export const examsData =[
    
];

export const assignmentsData =[
    
];

export const annoucementsData = [

];

export const calendarEvents = [
    {
        title:'Math',
        allDay:false,
        start:new Date(2024, 7, 12, 8, 0),
        end:new Date(2024, 7, 12, 8, 45)
    },
    {
        title:'English',
        allDay:false,
        start:new Date(2024, 7, 12, 9, 0),
        end:new Date(2024, 7, 12, 9, 45)
    },
    {
        title:'Biology',
        allDay:false,
        start:new Date(2024, 7, 12, 10, 0),
        end:new Date(2024, 7, 12, 10, 45)
    },
    {
        title:'Physics',
        allDay:false,
        start:new Date(2024, 7, 12, 11, 0),
        end:new Date(2024, 7, 12, 11, 45)
    },
]